version: '3'

services:

  qi_video_translation_dev_liujiaqi:
    image: qi_video_translation:dev_20241018
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qi_video_translation_api
    restart: unless-stopped
    network_mode: host
    tty: true
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - "./TEMP:/app/TEMP"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
